# Dining Room Light ON: Early Morning
- id: hue_dinrm_on_am
  alias: 'Dining Room Light ON: Early Morning'
  trigger:
    - platform: time
      at: "06:00:00"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_dinrm
      data:
        brightness_pct: 60
        transition: 2
  mode: single

# Lights OFF: Early and Late Morning
- id: lights_off_am
  alias: 'Lights OFF: Early and Late Morning'
  description: 'Turn OFF ALL Lights at 00:00 and 08:30'
  mode: single
  trigger:
    - platform: time
      at: "00:00:00"
    - platform: time
      at: "08:30:00"
  action:
    - service: script.lights_off

# Lights ON: 1 hr Before Sunset (Weather-Based)
- id: lights_on_pm_early
  alias: 'Lights ON: (-60m: weather-based)'
  mode: single
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  condition:
    - condition: template
      value_template: >
        {{ states('weather.forecast_home') | lower in ['cloudy', 'rainy'] }}
  action:
    - service: script.lights_on

# Lights ON: 30 min Before Sunset
- id: lights_on_pm_normal
  alias: 'Lights ON: (-30m)'
  mode: single
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    - condition: template
      value_template: "{{ is_state('group.lights', 'off') }}"
  action:
    - service: script.lights_on